### ISSUE TITLE
Rpc: Http parse

### ISSUE THREAD

**Issue by 4kangjc** [Tencent/flare#104]
呃这里`find("\r\n")`会不会更好一点, 如果字段中有`\n`会解析失败吧
```
Key: Value1\nValue2
```
https://github.com/Tencent/flare/blob/8b676027eeea0cff3a9a0544713c25cf72d66735/flare/rpc/protocol/http/buffer_io.cc#L207

**Comment by 0x804d8000** [comment]
https://www.rfc-editor.org/rfc/rfc2616#section-4.2

我理解field value是不能有\n的

**Comment by 4kangjc** [comment]
> https://www.rfc-editor.org/rfc/rfc2616#section-4.2
> 
> 我理解field value是不能有\n的

hmm, RFC好像没有禁止这个?

**Comment by 4kangjc** [comment]
> > <the OCTETs making up the field-value
> > and consisting of **either \*TEXT or combinations
> > of token, separators, and quoted-string**>
> 
> 这个应该不包含\n

好吧
