### ISSUE TITLE
Update blade build tools to more common build tools Bazel

### ISSUE THREAD

**Issue by pcman-zhang** [Tencent/flare#11]
Noticed this framework is using Tencent Blade as build tools, but with open sources, Bazel is more common.
Please update blade to Bazel

**Comment by CodEnFisH** [comment]
Agreed. I think for an opensource project to be popular, it's better to use a well-established building system.
Not to say which is which building system is better -- I believe Blade shares lot commonality with Bazel, and does better jobs on many aspects -- it's just easier for the community to adopt a new opensource project when it can be built with their existing building systems.

Please consider.

**Comment by hanhiver** [comment]
Agree! Or in a alternative way, cmake is also a good choice.

**Comment by 0x804d8000** [comment]
Thank you all for the feedback about the building process.

I do agree one or more alternatives would be good, but it's not on our priority list for the moment.

We'll take a deeper look at this once we have more time.

**Comment by 0x804d8000** [comment]
See #121 .
