### ISSUE TITLE
update blade

### ISSUE THREAD

**Issue by 4kangjc** [Tencent/flare#111]
https://github.com/chen3feng/blade-build/pull/996
现在Python版本高于3.10是没办法编译的
![image](https://github.com/Tencent/flare/assets/73515066/c6cd5880-da97-439e-bb43-aa2a2c48ae8b)

**Comment by 4kangjc** [comment]
https://github.com/Tencent/flare/blob/d6534086041ae6e31504870db8db88fc391c7e66/.gitattributes#L4
之前有自带Python2.7吗？现在在3rd里找不到了

**Comment by 4kangjc** [comment]
我没看懂这个blade.zip，能解释一下吗，为啥不用对它解压缩就可以直接用

**Comment by 4kangjc** [comment]
![image](https://github.com/Tencent/flare/assets/73515066/df590cc8-bef0-4985-9f6b-cd1fd2c121de)

ARM 架构下编不了

**Comment by 0x804d8000** [comment]
arm那个感觉是qemu的问题。直接能用blade.zip好像是Python的特性。

blade好像有个自动打包的脚本，@chen3feng 陈老师能说下打包方法吗

**Comment by 0x804d8000** [comment]
Python2.7那个应该是不小心把内部的gitattributes复制出来了，内部确实是仓库里面带了个Python

**Comment by 4kangjc** [comment]
> Python2.7那个应该是不小心把内部的gitattributes复制出来了，内部确实是仓库里面带了个Python

OK

**Comment by USTB-JXY** [comment]
ln -sf /usr/bin/python2 /usr/bin/python
可以解决python 
![image](https://github.com/Tencent/flare/assets/49434108/b7b10143-314e-47e5-a1c5-f7d969561e21)

**Comment by 4kangjc** [comment]
> ln -sf /usr/bin/python2 /usr/bin/python 可以解决python ![image](https://user-images.githubusercontent.com/49434108/258038971-b7b10143-314e-47e5-a1c5-f7d969561e21.png)

嗯，是可以使用python2，不过这条isssues是要求升级blade以适配python3.10以上的版本

**Comment by chen3feng** [comment]
> arm那个感觉是qemu的问题。直接能用blade.zip好像是Python的特性。
> 
> blade好像有个自动打包的脚本，@chen3feng 陈老师能说下打包方法吗

Run `dist_blade`
