### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by 4kangjc** [Tencent/flare#115]
- flare中的`FLARE_LOG_INFO`除了`fmt::format`优化还有其他的么? 有这么一个问题, 假设将日志等级设成WARN, 那么下面这条`Hello World`的日志一定不会打, 但是这条LOGMessage却还是会生成, 也就是说EXPECT会失败.
```cpp
  FLARE_LOG_INFO("{}", []() -> const char* {
    EXPECT_FALSE(true);
    return "Hello World!";
  }());
```
- 在source code中改变日志等级, 只能用glog提供的`FLAGS_minloglevel`么? flare为什么没有提供, 我在`logging_test`中使用`FLAGS_minloglevel`还得链接上`glog`, 这个好像是blade的问题,  然后blade直接编译出来的binary也不能直接运行(我想通过-minloglevel改变日志等级), 这两点和bazel不太一样, 以前我还没注意.
`./blade-bin/flare/base/internal/logging_test: error while loading shared libraries: libfmt.so.7: cannot open shared object file: No such file or directory`

**Comment by 0x804d8000** [comment]
1，应该不会求值，glog里面我记得有判断。如果还是求值了应该是bug。

2，是的，本身是一个针对glog的wrapper，内部有些脚本依赖glog的格式，而且实践中也够用，所以就没有自己搞一套独立的了。blade编译出来改了rpath，比较简单的办法是去build64_xxx/path/to/xxx_test.runfiles下面运行。

**Comment by 4kangjc** [comment]
> 1，应该不会求值，glog里面我记得有判断。如果还是求值了应该是bug。
> 
> 2，是的，本身是一个针对glog的wrapper，内部有些脚本依赖glog的格式，而且实践中也够用，所以就没有自己搞一套独立的了。blade编译出来改了rpath，比较简单的办法是去build64_xxx/path/to/xxx_test.runfiles下面运行。

1. 我尝试过了, 确实是会去执行这个函数, 可以看一下 https://github.com/google/glog/issues/463
所以我们要不要优化这点
2. 好的

**Comment by 0x804d8000** [comment]
应该是我记错了（或者内部的魔改过）。

这儿确实值得处理下，不然尤其是debug级别的日志，始终求值对用户不太友好，可能需要开会删了加加了删。

感觉可以用if (log enabled)套一层之类的。

**Comment by 4kangjc** [comment]
> 应该是我记错了（或者内部的魔改过）。
> 
> 这儿确实值得处理下，不然尤其是debug级别的日志，始终求值对用户不太友好，可能需要删了加加了删。
> 
> 感觉可以用if (log enabled)套一层之类的。

感觉
```cpp
#define FLARE_LOG_INFO(...)                                              \
  if (GLOG_INFO >= GFLAGS_minloglevel)
    LOG(INFO) << ::flare::internal::logging::FormatLog(__FILE__, __LINE__, \
                                                       __VA_ARGS__)
```
或者直接用LOG_IF也可以
``` cpp

#define FLARE_LOG_INFO(...)                                              \
  LOG_IF(INFO, GLOG_INFO >= GFLAGS_minloglevel) 
                 << ::flare::internal::logging::FormatLog(__FILE__, __LINE__, \
                                                     __VA_ARGS__)
```

**Comment by 4kangjc** [comment]
> 应该是我记错了（或者内部的魔改过）。
> 
> 这儿确实值得处理下，不然尤其是debug级别的日志，始终求值对用户不太友好，可能需要删了加加了删。
> 
> 感觉可以用if (log enabled)套一层之类的。

debug级别日志指DLOG()系列吗? 这个倒还好, 如果在Release模式下, DLOG直接展开为空, 不会去求值

**Comment by 0x804d8000** [comment]
迷糊了，想着还有个LOG_DEBUG这种级别去了……

那现在这样我觉得倒没什么，正常的代码里面INFO/+的日志也不会很多，感觉优化必要不大

**Comment by 4kangjc** [comment]
> 迷糊了，想着还有个LOG_DEBUG这种级别去了……
> 
> 那现在这样我觉得倒没什么，正常的代码里面INFO/+的日志也不会很多，感觉优化必要不大

OK

**Comment by 4kangjc** [comment]
> 



> 
> 2，是的，本身是一个针对glog的wrapper，内部有些脚本依赖glog的格式，而且实践中也够用，所以就没有自己搞一套独立的了。blade编译出来改了rpath，比较简单的办法是去build64_xxx/path/to/xxx_test.runfiles下面运行。

如果我要运行`flare/base/internal/logging_test`, 要倒`flare/base/internal/logging_test.runfiles`下面执行`../logging_test`?
![image](https://github.com/Tencent/flare/assets/73515066/27b59300-8bd5-482e-beb0-90aec15c2e5e)
