### ISSUE TITLE
请问有合适的源码阅读顺序吗

### ISSUE THREAD

**Issue by yinghaoyu** [Tencent/flare#131]
代码质量很高，配合`doc`阅读也有点吃力，目前卡在`flare/base`这个目录，关联的东西很多，不知道从哪下手了。希望后续`doc`能有图~

**Comment by yinghaoyu** [comment]
不知道各位`contributor`是用的什么编辑器，`vscode`跳转会失效，`vim`下用`lsp`插件也不行呢，blade编译也不会生成`compile_command.json`这个文件

**Comment by yinghaoyu** [comment]
`lsp`问题解决了，使用这个工具[bazel-compile-commands-extractor](https://github.com/hedronvision/bazel-compile-commands-extractor)生成`compile_commands.json`，希望对后来者有所帮助。

**Comment by 4kangjc** [comment]
blade生成`compile_commands.json`可以看一下 https://github.com/Tencent/flare/issues/48

**Comment by 4kangjc** [comment]
代码阅读顺序这个得看自己的关注点是什么，取决于个人

**Comment by yinghaoyu** [comment]
Thanks.
