### ISSUE TITLE
对GetFreeCount的取值比较困惑

### ISSUE THREAD

**Issue by yinghaoyu** [Tencent/flare#132]
```cpp
std::size_t GetFreeCount(std::size_t upto) {
  return std::min(upto, std::max(upto / 2, kMinimumFreePerWash));
}
```
1. 当 `upto > 2 * kMinimumFreePerWash`，取 `upto / 2` 显然大于 `kMinimumFreePerWash`。
2. 当 `2 * kMinimumFreePerWash >= upto >= kMinimumFreePerWash `，取 `kMinimumFreePerWash`。
3. 当 `kMinimumFreePerWash > upto `，取 `upto` 显然小于 `kMinimumFreePerWash`。

请问这样取值的意义在哪？[L32C1-L32C1](https://github.com/Tencent/flare/blob/f0bf9a486834c00aacd421f9150e84ec9137a879/flare/base/object_pool/thread_local.cc#L32C1-L32C1)

**Comment by 0x804d8000** [comment]
没理解问题，是说觉得这儿有bug吗

**Comment by yinghaoyu** [comment]
不是`bug`，是觉得为什么要以这个逻辑取值

**Comment by 0x804d8000** [comment]
限制upto是为了避免一次释放太多阻塞太久，设置一个下界是为了避免每次释放太少导致反复跑这个逻辑

**Comment by yinghaoyu** [comment]
谢谢

**Comment by yinghaoyu** [comment]
谢谢

**Comment by yinghaoyu** [comment]
https://github.com/Tencent/flare/commit/9cc00d310594f1be59c4a9d8ba082f0e052bad66#r137532406
