### ISSUE TITLE
Question About Future and Async: Will it blocking until the the result has been product

### ISSUE THREAD

**Issue by mapleFU** [Tencent/flare#14]
Since that brpc do not has the `future` type, and `std::async` will:
> If the std::future obtained from std::async is not moved from or bound to a reference, the destructor of the std::future will block at the end of the full expression until the asynchronous operation completes, essentially making code such as the following synchronous

And `folly::Future` will detach when destructor.

I have through the documents:
1. https://github.com/Tencent/flare/blob/master/flare/doc/fiber.md
2. https://github.com/Tencent/flare/blob/master/flare/doc/future.md

I didn't find anywhere that says if it will block or detach when destruct. And I go through the code, and find it will share a `std::shared_ptr<Core>`, and it will do like detached. Did I catched it?

**Comment by 0x804d8000** [comment]
Yes, it's detached.

**Comment by mapleFU** [comment]
@0x804d8000 would you mind putting it to document? Since it might be confusing when we're using it.

**Comment by 0x804d8000** [comment]
Will do. Thanks for bringing this up.

**Comment by 0x804d8000** [comment]
Done via #17 .
