### ISSUE TITLE
问一个非常诡异的用例

### ISSUE THREAD

**Issue by yinghaoyu** [Tencent/flare#140]
1. https://github.com/Tencent/flare/tree/master/flare/base/compression/compression_test.cc
运行`./compression_test gzip`
```cpp
  std::string Compress(
      std::function<bool(Compressor*, CompressionOutputStream* out)> f) {
    if (!with_test_output_stream_) {
      NoncontiguousBufferBuilder builder;
      NoncontiguousBufferCompressionOutputStream out(&builder);
      auto&& c = MakeCompressor(method_);  //  调试这里一直返回nullptr
      EXPECT_TRUE(c);
```

2. https://github.com/Tencent/flare/blob/master/flare/base/compression_test.cc
这个用例正常运行。

`gzip`都已经在[cpp](https://github.com/Tencent/flare/blob/master/flare/base/compression/gzip.cc)文件`FLARE_COMPRESSION_REGISTER_COMPRESSOR("gzip", GzipCompressor);`注册过了，这是啥情况？

**Comment by 0x804d8000** [comment]
没太理解，是说编译以后直接运行`compression_test gzip`失败了吗，但是这个compression_test感觉接受不了参数啊🤔

**Comment by yinghaoyu** [comment]
第1个用例`SetUp()`函数会读取参数的。第2个用例是正常的，作为参照。

**Comment by 0x804d8000** [comment]
你的执行方式是

```text
~/flare/build64_release/flare/base/compression_test.runfiles]% LD_LIBRARY_PATH=. ../compression_test gzip
```

这样吗

我这样执行看起来命令行参数`gzip`被忽略了，跟直接执行`LD_LIBRARY_PATH=. ../compression_test`效果是一样的

你也可以试试把`method_`打出来看看是不是符合预期的内容

**Comment by yinghaoyu** [comment]
你看的是第二个用例，这个是对的。我说的是第一个用例，`method_`打印是符合我预期的。

**Comment by 0x804d8000** [comment]
你运行的是**master代码**生成的`flare/base/compression/compression_test`吗？

我试了下不管不传命令行参数或者传命令行参数`gzip`，输出是一样的。而且根据我的理解，gtest也不会因为命令行传入了一个不以`-`开头的参数就改变行为。

**Comment by 0x804d8000** [comment]
用cmake的话注意一下https://github.com/Tencent/flare/blob/master/flare/base/compression/BUILD#L55 link_all_symbols，对应于-Wl,--whole-archive

不然链接器可能会把自动注册的这些文件丢掉

https://stackoverflow.com/questions/805555/ld-linker-question-the-whole-archive-option

**Comment by yinghaoyu** [comment]
谢谢，原来如此。
