### ISSUE TITLE
编译时间太长

### ISSUE THREAD

**Issue by yinghaoyu** [Tencent/flare#143]
```cpp
bash -c "./blade test ..."
```
在`WSL2 ubuntu20.04`下编译要半个多小时，有时候我可能只改了一个`.h`文件都要这么久，请问有什么解决方案吗

**Comment by 0x804d8000** [comment]
这个没太多办法，blade已经是增量编译了，现在只编译了确实需要重新编译的代码。

公司里面因为有分布式编译/大规格开发机，所以对编译速度感知也不太强

**Comment by yinghaoyu** [comment]
分布式编译是指你主页的[yadcc](https://github.com/Tencent/yadcc)吗

**Comment by 0x804d8000** [comment]
对的

**Comment by 0x804d8000** [comment]
不过如果有其他分布式编译环境（比如distcc)其实也可以直接用，flare没有跟具体的编译加速工具链绑定
