### ISSUE TITLE
调试相关

### ISSUE THREAD

**Issue by yinghaoyu** [Tencent/flare#145]
直接运行`./blade-bin/flare/rpc/server_group_test`会提示缺少动态库，通过`blade build ...`编译生成的二进制文件需要怎么调试啊？

**Comment by 0x804d8000** [comment]
cc_binary应该可以直接运行。

cc_test一般是blade test的。blade test之后会在./blade-bin/flare/rpc/server_group_test.runfiles里面建立好环境，进入这个目录然后把LD_LIBRARY_PATH指向.就可以运行这个test了，比如通过../server_group_test运行。

**Comment by chen3feng** [comment]
为了减少存储空间消耗，cc_test默认是动态链接的，通过test子命令运行时会提前设置环境。直接单独运行会因为找不到动态库路径而失败。可以加上dynamic_link=False强制指定静态链接。

**Comment by yinghaoyu** [comment]
谢谢二位。

答案补充，在`flare/rpc/BUILD`文件中，给具体的测试用例添加`dynamic_link = False`，如下：
```
cc_test(
  name = 'server_test',
  srcs = ['server_test.cc'],
  deps = [
    ':http',
    ':rpc',
    '//flare/fiber:fiber',
    '//flare/net/http:http_client',
    '//flare/rpc/internal:stream_call_gate',
    '//flare/rpc/protocol:stream_service',
    '//flare/testing:echo_service_proto_flare',
    '//flare/testing:endpoint',
    '//flare/testing:main',
    '//thirdparty/jsoncpp:jsoncpp',
  ],
  dynamic_link = False
)
```
然后然后重新编译。
