### ISSUE TITLE
Fiber scheduling takes too long

### ISSUE THREAD

**Issue by Fin-chan** [Tencent/flare#146]
```
auto start_time = flare::ReadSteadyClock();
flare::fiber::Async([start_time]{
	auto end_time = flare::ReadSteadyClock();
	const auto scheduling_time = std::chrono::duration_cast<std::chrono::microseconds>(end_time - start_time);
	// user code
});
```

flare::fiber::Async() opens a fiber concatenation to execute and found that the scheduling_time is long, is there any way to analyze and optimize it?

**Comment by yinghaoyu** [comment]
Try to use [`perf`](https://perf.wiki.kernel.org/index.php/Main_Page).

**Comment by 0x804d8000** [comment]
Internals of fiber scheduling are exposed via https://github.com/Tencent/flare/blob/master/flare/doc/debugging.md . 

You might be interested in https://github.com/Tencent/flare/blob/master/flare/fiber/detail/scheduling_group.cc#L72 in specific. 

Please note that you need open a port via flare::Server to access these variables.

**Comment by Fin-chan** [comment]
I fixed the problem of long scheduling times for fiber. Thx
