### ISSUE TITLE
Can it support machines with large cores

### ISSUE THREAD

**Issue by Fin-chan** [Tencent/flare#147]
Can it support machines with large cores like 256 cores

**Comment by 0x804d8000** [comment]
It should work on such machine, but internally we've only tested Flare on machines with upto 90 vcores.

**Comment by Fin-chan** [comment]
It can still run at 70~80% CPU utilization on a 128-core machine, but can't do it on 256 cores.
Can you use the perf tool to optimize flare performance by using the echo example? How should I do performance optimization for flare

**Comment by 0x804d8000** [comment]
I guess this has something to do with [the scheduling parameters](https://github.com/Tencent/flare/blob/master/flare/fiber/detail/scheduling_parameters.cc#L103).

To avoid high lock contention, internally we split cores into several "scheduling group", and fibers are only scheduled inside it's assigned group. 

However, this can lead to load unbalance, especially if the workload is computation heavy.

I suggest you to try tuning these parameters via [--flare_scheduling_group_size](https://github.com/Tencent/flare/blob/master/flare/fiber/runtime.cc#L42-L46) or [--flare_fiber_scheduling_optimize_for](https://github.com/Tencent/flare/blob/master/flare/fiber/runtime.cc#L79-L89) and see if that makes a change.

If your workload sleeps or blocks often, you might want to increase [--flare_concurrency_hint](https://github.com/Tencent/flare/blob/master/flare/fiber/runtime.cc#L79-L89) as well.

**Comment by Fin-chan** [comment]
Thanks~ its done
