### ISSUE TITLE
本地构建/开始使用打不开

### ISSUE THREAD

**Issue by codingcai** [Tencent/flare#4]
你好，在使用时碰到两个问题：

1） 本地构建

本地构建使用./blade build ...时 ， 会提示以下错误：
Blade(error): This repository need GIT LFS, see README.md
Blade(error): Blade will exit...

打开对应提示文件，发现blade.zip 是小于 判断的1024字节， 请问这个是什么原因呢？

2） 开始使用 指向的文档链接打不开：https://github.com/Tencent/flare/blob/master/flare/doc/getting-started.md

谢谢

**Comment by 0x804d8000** [comment]
感谢反馈。

`thirdparty/`下面很多文件是通过LFS存储的，所以需要安装git-lfs来拉取文件。git-lfs的使用可以参考例如https://gitee.com/help/articles/4235。

安装了`git-lfs`之后可以：

- 重新clone一次，或者
- `git lfs pull`

之后`blade.zip`（和其他thirdparty/下面的包）应该是正常的可以用于编译了。稍后我会在`README.md`中说明这一点。

`getting-started.md`同步的时候删掉了，因为里面的内容挪到了根目录的`README.md`，但是链接忘了删。稍后我把链接也处理掉。
