### ISSUE TITLE
How to build flare using blade?

### ISSUE THREAD

**Issue by zjyuan** [Tencent/flare#45]
Hi there,
I have installed blade and ninja but don't know how to build flare or examples in flare project. I have no experience of blade and ninja. I think I installed blade and ninja correctly. Below is some log:

`luis@ubuntu:/mnt/hgfs/E/flare/flare/example$ blade -h
usage: blade [-h] [--version] {build,run,test,clean,query,dump} ...

blade <subcommand> [options...] [targets...]

positional arguments:
  {build,run,test,clean,query,dump}
                        Available subcommands
    build               Build specified targets
    run                 Build and runs a single target
    test                Build the specified targets and runs tests
    clean               Remove all blade-created output
    query               Execute a dependency graph query
    dump                Dump specified internal information

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
luis@ubuntu:/mnt/hgfs/E/flare/flare/example$ ninja --version
1.10.0
luis@ubuntu:/mnt/hgfs/E/flare/flare/example$ 
`

**Comment by 0x804d8000** [comment]
Try `./blade build ...`

**Comment by zjyuan** [comment]
> Try `./blade build ...`

Thanks for reply. I did try that. Here is the error log:
luis@ubuntu:/mnt/hgfs/E/flare$ ./blade build ...
Blade(error): This repository need GIT LFS, see README.md
Blade(error): Blade will exit...
luis@ubuntu:/mnt/hgfs/E/flare$ which git-lfs
/usr/bin/git-lfs
luis@ubuntu:/mnt/hgfs/E/flare$ 
luis@ubuntu:/mnt/hgfs/E/flare$ git-lfs --version
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)

It seems blade can't find git-lfs.

**Comment by 0x804d8000** [comment]
It seems that Git LFS didn’t work as intended when the repository was cloned. (Haven’t yet executed `git lfs install`?)

You may want to try executing `git lfs pull` and build again.

**Comment by zjyuan** [comment]
Thanks.It works for me.
