### ISSUE TITLE
blade Support generating compdb

### ISSUE THREAD

**Issue by XlousZ** [Tencent/flare#48]
I see [generating compdb](https://github.com/chen3feng/blade-build/issues/480) in [blade-build](https://github.com/chen3feng/blade-build)

**Comment by 0x804d8000** [comment]
I’m not clear about what you’re asking or proposing, mind to elaborate more?

**Comment by XlousZ** [comment]
I want to generate `compile_commands.json`, so i can generate accurate C++ indexes by clangd

**Comment by 0x804d8000** [comment]
I think it's already supported by `blade`, e.g.:

```bash
./blade dump --compdb --to-file output.json ...
```

You may refer to [manual of `blade`](https://github.com/chen3feng/blade-build/blob/master/doc/en/command_line.md) for more details.

**Comment by XlousZ** [comment]
> I think it's already supported by `blade`, e.g.:
> 
> ```shell
> ./blade dump --compdb --to-file output.json ...
> ```
> 
> You may refer to [manual of `blade`](https://github.com/chen3feng/blade-build/blob/master/doc/en/command_line.md) for more details.

Thanks! I try `./blade dump --compdb --to-file output.json`, and successfuly generate compile_commands.json

After carefully reading, i noted `The options supported by different subcommands are different. Please run blade <subcommand> --help to view` in [manual of `blade`](https://github.com/chen3feng/blade-build/blob/master/doc/en/command_line.md)
