### ISSUE TITLE
Why use std::common_type in TryParseTraits

### ISSUE THREAD

**Issue by npuichigo** [Tencent/flare#54]
Could anyone help to explain why `std::common_type` is need [here](https://github.com/Tencent/flare/blob/master/flare/base/string.h#L110) instead of just using `T()`?
```c++
template <class T, class>
struct TryParseTraits {
  // The default implementation delegates calls to `TryParse` found by ADL.
  template <class... Args>
  static std::optional<T> TryParse(std::string_view s, const Args&... args) {
    return TryParse(std::common_type<T>(), s, args...);
  }
};
```

**Comment by 0x804d8000** [comment]
So as not to instantiate `T`, whose default constructor (if there’s one at all) might be non-trivial or have side effect.

**Comment by npuichigo** [comment]
Thanks for your quick reply
