### ISSUE TITLE
http json 转 protobuf message 出错

### ISSUE THREAD

**Issue by xuexcy** [Tencent/flare#61]
https://github.com/Tencent/flare/blob/6d3bf3c46ab5e4178a0676de6d1172930bc45a3a/flare/rpc/protocol/protobuf/gdt_json_proto_conversion.cc#L326

这里处理repeated字段，是不是应该写成 item.asString()   ,  而不是value.asString()，因为value是一个数组。

} else if (auto opt = TryParse<valuetype>(item.asString())) {

**Comment by 0x804d8000** [comment]
是的，感谢反馈。稍后我修一下。

**Comment by 0x804d8000** [comment]
Fixed via #62.
