### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by 4kangjc** [Tencent/flare#64]
# 编译环境 gcc 版本 11.2.0 (GCC)
![flare2](https://user-images.githubusercontent.com/73515066/166140861-5570055b-b2f9-4ecb-a997-fe63b29e708b.png)
## 这里缺少头文件, 加入头文件 optional 就行
![flare](https://user-images.githubusercontent.com/73515066/166140731-73a4ff17-b9a0-4e70-9f59-d20df2d412d8.png)
## 这个我暂时将/usr/include/sys/cdefs.h中的__glibc_has_attribute (__const__)删了,希望有更好的解决办法
![flare3](https://user-images.githubusercontent.com/73515066/166140937-0505ca0a-34ff-4c9d-ae0c-f233d4e80807.png)

**Comment by 0x804d8000** [comment]
`__const__`那个有点麻烦，原意是为了解决gcc对访问`errno`的缓存问题（参考https://github.com/apache/incubator-brpc/blob/master/docs/cn/thread_local.md ），但是看起来这个workaround跟新版glibc冲突了。

其实这儿还有一些类似的问题，都是对tls的访问的缓存上（errno那个因为多了个函数调用，把问题变成了const这个attribute）。之前在开了tsan的情况下`fiber_entity.h`里面也出过问题，后来把一些inline干掉了绕过去了。

针对这些缓存问题https://www.mail-archive.com/gcc@gcc.gnu.org/msg96208.html 有一些讨论，不过实现起来看起来有些困难。

可以试试把几个BUILD里面的`extra_cppflags = ['-D__const__=']`换成`extra_cppflags = ['-D__const__=hot']`，可能可以作为一个workaround的workaround。

**Comment by 0x804d8000** [comment]
另一种办法（preferably）是干脆不用`errno`了，单独提供一个独立函数`int FiberSafeGetLastError();`。然后把现在的`errno`都换成调用这个函数。

这个函数的实现（`{ return errno; }`）放在.cc里，这样编译器在call site就没法做CSE了，保证每次都会实际访问`errno`。感觉上这么搞也可以解决这个问题，然后就不用`-D__const__=`了。

后面我改成这样试试看。

**Comment by 4kangjc** [comment]
恩恩 好

**Comment by 4kangjc** [comment]
> 另一种办法（preferably）是干脆不用`errno`了，单独提供一个独立函数`int FiberSafeGetLastError();`。然后把现在的`errno`都换成调用这个函数。
> 
> 这个函数的实现（`{ return errno; }`）放在.cc里，这样编译器在call site就没法做CSE了，保证每次都会实际访问`errno`。感觉上这么搞也可以解决这个问题，然后就不用`-D__const__=`了。
> 
> 后面我改成这样试试看。

这个问题好像还是存在

**Comment by 4kangjc** [comment]
> 

![image](https://user-images.githubusercontent.com/73515066/204094669-a83179fe-f2c4-4939-85dc-8b4998a940c9.png)

**Comment by 4kangjc** [comment]
```bash
./flare/base/demangle.h: In function 'std::string flare::GetTypeName(T&&) [with T = const Message&]':
./flare/base/demangle.h:33:52: error: 'nonnull' argument 'o' compared to NULL [-Werror=nonnull-compare]
   33 |   return Demangle(typeid(std::forward<T>(o)).name());

```

**Comment by 4kangjc** [comment]
https://github.com/4kangjc/flare/actions/runs/3556457729/jobs/5973838355
https://github.com/4kangjc/flare/actions/runs/3556457729/jobs/5973838418

**Comment by 4kangjc** [comment]
Ubuntu-latest workflows will use Ubuntu-22.04
https://github.com/actions/runner-images/issues/6399

**Comment by 4kangjc** [comment]
![Screenshot_20221127_121425](https://user-images.githubusercontent.com/73515066/204118963-46847964-6490-42a4-b845-79b6f7f76b00.png)
GCC11 除catch2的那个问题外，应该编译没啥问题了
GCC12 问题很大

**Comment by 0x804d8000** [comment]
`__const__`之前应该是改漏了，#80 试着修了一下。

catch2那个似乎是opentracing跑去用clang编译了，回头看看能不能强制指定gcc试试。

**Comment by 4kangjc** [comment]
> `__const__`之前应该是改漏了，#80 试着修了一下。
> 
> catch2那个似乎是opentracing跑去用clang编译了，回头看看能不能强制指定gcc试试。

嗯，`__const__`已经修好了。
`catch2`应该是这个问题 https://github.com/catchorg/Catch2/issues/2178

**Comment by 4kangjc** [comment]
GCC12 有一个 `protobuf`的问题，好像是这个
https://github.com/protocolbuffers/protobuf/issues/7140
![Screenshot_20221209_142047](https://user-images.githubusercontent.com/73515066/206639774-e718cd0f-c31e-44e6-99f7-64b8d12585c1.png)

**Comment by 4kangjc** [comment]
> GCC12 有一个 `protobuf`的问题，好像是这个 [protocolbuffers/protobuf#7140](https://github.com/protocolbuffers/protobuf/issues/7140) ![Screenshot_20221209_142047](https://user-images.githubusercontent.com/73515066/206639774-e718cd0f-c31e-44e6-99f7-64b8d12585c1.png)

或者加`'-Wno-array-bounds'`和`'-Wno-stringop-overread'`
![Screenshot_20221209_143617](https://user-images.githubusercontent.com/73515066/206640301-1d9ebe01-68f7-4414-a857-bc5092adec29.png)

**Comment by 4kangjc** [comment]
@0x804d8000 我可以在`.gitignore`里加上
```shell
# vscode clangd
/.cache
/compile_commands.json
```
吗？

**Comment by 4kangjc** [comment]
![Screenshot_20221209_182333](https://user-images.githubusercontent.com/73515066/206681137-7dafa057-a177-4aa1-a12e-64ff3a39ab07.png)
这个应该是GCC12的误报

**Comment by 4kangjc** [comment]
> ![Screenshot_20221209_182333](https://user-images.githubusercontent.com/73515066/206681137-7dafa057-a177-4aa1-a12e-64ff3a39ab07.png) 这个应该是GCC12的误报

https://github.com/Tencent/flare/blob/37be0123824a9c53d963c5430c9f991fdaf64c0a/flare/rpc/protocol/http/builtin/exposed_vars_handler.cc#L60

改成`abs_path = std::string("/");`就能编译通过

**Comment by 4kangjc** [comment]
![Screenshot_20221209_184418](https://user-images.githubusercontent.com/73515066/206684841-c8fbbe74-58cc-4c93-a720-6facf5268190.png)

**Comment by 4kangjc** [comment]
> `__const__`之前应该是改漏了，#80 试着修了一下。
> 
> catch2那个似乎是opentracing跑去用clang编译了，回头看看能不能强制指定gcc试试。

把`opentracing`的test关了吧
