### ISSUE TITLE
Blade(error): File "//../../BUILD" does not exist

### ISSUE THREAD

**Issue by zbhxlj** [Tencent/flare#65]
![image](https://user-images.githubusercontent.com/56293376/166488290-6d947be2-7a3d-4458-9d0a-5ceb791fb689.png)

**Comment by 0x804d8000** [comment]
看起来是shell吧…传给blade之前展开成了../..，可以看看shell的文档怎么禁止这个展开，或者用blade build //path/to:target

**Comment by zbhxlj** [comment]
感谢，是zsh的问题，已经解决
