### ISSUE TITLE
add constexpr

### ISSUE THREAD

**Issue by 4kangjc** [Tencent/flare#67]
https://github.com/Tencent/flare/blob/2e2f59da08bf988d970c1160fe07746d009075d9/flare/base/function.h#L305
这里加个constexpr吧,虽然编译器会优化掉

**Comment by 0x804d8000** [comment]
感谢反馈。这个看着应该没太大影响，回头我抽空处理下。

**Comment by 4kangjc** [comment]
恩 好的
