### ISSUE TITLE
DetachTimer的设计权衡是怎样的？

### ISSUE THREAD

**Issue by zbhxlj** [Tencent/flare#70]
`DetachTimer()`是应用于怎样的场景呢？ 注释中说 can be helpful in fire-and-forget cases. 我的理解是单次定时任务（不重复定时），但已经存在了对应的`CreateTimer()`接口了，对于`DetachTimer`的设计思考以及具体作用不太理解。

**Comment by 0x804d8000** [comment]
释放内部引用计数，避免内存泄漏
